# This is the configuration file for tasosh

# General configurations
auto_exec=true

# Logs configurations
keep_arg_on_logs=true
save_logs_to_file=true

# Prompt configurations
prompt="%USER%@%HOST%:%POS%$ "

# Debug configurations
debug_mode=false

# Plugins configurations
apply_plugins=true;
